import Sidebar from "@/components/sidebar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full flex">
          {/* <Sidebar /> */}
          <div className="w-full min-h-screen">{children}</div>
        </main>
      </body>
    </html>
  );
}
